### ISSUE TITLE
Конференции

### ISSUE THREAD

**Issue by koninka** [koninka/fefu-social-network#104]
Необходимо сделать следующее:
  1. Создание чата с несколькими пользователями (конференция) с возможностью приглашения юзеров, исключения юзера из конфы если я создатель или имею на это право, указания темы конфы и выходом из нее. См vk.com.
    * Не забыть про проверки доступа (человек не являющийся членом конфы не может отправлять сообщения в нее, удалять из конфы других людей, менять тему).
  2. Сделать окна диалога табами.
  3. К уже существующему функционалу "Написать сообщение" по имени пользователя добавить возможность указания нескольких пользователей. Таким образом при указании нескольких адресатов автоматически создается новая конфа с этими ребятами. См vk.com
  4. Весь код, который после обращения к методам `ThreadRepository` преобразует данные в необходимый формат, требуется перенести в репозиторий.
Пример: код `$r[] = [..]`, представленный ниже, необходимо перенести в репозиторий:
```php
  <?php
          $threads = $threadRepo->getThreadListForUser($user->getId());
          $r = [];
          // TODO: try to pull this in single DB request instead of loop
          foreach ($threads as $t) {
              $ou = $threadRepo->getOtherUserInThread($t->getId(), $user->getId());
              $r[] = [
                  'id' => $t->getId(),
                  'topic' => $t->getTopic(),
                  'userId' => $ou->getId(),
                  'userName' => $ou->getFirstName() . " " . $ou->getLastName()
              ];
          }
```

**Comment by USKamicadze** [comment]
Мне @USKamicadze
