### ISSUE TITLE
Усовершенстование системы общения пользователей

### ISSUE THREAD

**Issue by koninka** [koninka/fefu-social-network#96]
На данный момент есть pvp чаты. Необходимо сделать следующее:
  1. На странице диалога выводить аватарки собеседник(а/ов) (см. vk.com).
  2. Сделать страницу диалога не бесконечно расширяющимся блоком, а скролящимся (если сообщения превышают длину экрана).
  3. Сделать отправку сообщения не по id юзера, а по имени (инпут с простым поиском).
  4. Добавить кнопку "Отправить сообщение" на странице пользователя.
  5. Добавить для сообщения флаг прочитано/не прочитано.
    * В меню выводить кол-во непрочитанных сообщений.
    * Если пользователь находится в диалоге, то автоматически помечать сообщение как прочитанное при условии, что оно попало в видимую часть экрана (поскольку блок с сообщениями будет скролится, то человек будет обязан пролистать до самого первого непрочитанного сообщения в этом диалоге).
  6. Реализовать все todo, оставленные в коде предыдущим исполнителем.
  7. Перевод native query в dql (пара запросов).
  8. Весь код, который после обращения к методам `ThreadRepository` преобразует данные в необходимый формат, требуется перенести в репозиторий.
Пример: код `$r[] = [..]`, представленный ниже, необходимо перенести в репозиторий:
```php
  <?php
          $threads = $threadRepo->getThreadListForUser($user->getId());
          $r = [];
          // TODO: try to pull this in single DB request instead of loop
          foreach ($threads as $t) {
              $ou = $threadRepo->getOtherUserInThread($t->getId(), $user->getId());
              $r[] = [
                  'id' => $t->getId(),
                  'topic' => $t->getTopic(),
                  'userId' => $ou->getId(),
                  'userName' => $ou->getFirstName() . " " . $ou->getLastName()
              ];
          }
```

**Comment by USKamicadze** [comment]
я возьму @USKamicadze
